# Generated by Django 5.1.2 on 2024-10-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0002_alter_alumnot_options_alter_alumnot_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
    ]
